language: python
python:
  - "2.7"
install:
  - pip install pipenv
  - pipenv install --dev
script: "pipenv run python manage.py test"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database helios;' -U postgres
before_install:
  - export BOTO_CONFIG=/dev/null

